### PR TITLE
Minor copy edits

### PR DESCRIPTION
**Pull request by smasongarrison**
Here's the pull request with the minor copy edits I made while reviewing your paper. Nice job!

### CODE REVIEW

**Comment by jamesuanhoro** [comment]
Thank you again @smasongarrison for the changes here, they are much appreciated. Just updating the README.md file based on your changes to the README.Rmd prior to committing.

**Comment by smasongarrison** [comment]
Happy to help! Genuinely, the process of peer reviewing was very helpful. It's gotten me thinking about doing the final push for a few of my own packages. I'll be curious how your department views JOSS papers.

**Comment by jamesuanhoro** [comment]
Yeah, it's a very nice process. Funny: I had my annual review meeting with my dept. chair and wanted to ask this question, then completely forgot, lol. I think I'll email her instead. JOSS lets you retrieve paper metrics so hoping that works for the department.

**Comment by smasongarrison** [comment]
Lol. I was able to negotiate for software packages (as long as I maintained them) to count as research in my annual reviews. They're a little overpowered at the moment, so I've been thinking about how to nerf them. And JOSS might be a way to do that.

**Pull request merged**
